# Generated by Django 4.2 on 2025-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_status_oldpaper_status_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpaper',
            name='course',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
