# Generated by Django 4.2 on 2025-06-27 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_oldpaper_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oldpaper',
            name='university',
            field=models.CharField(choices=[('GTU', 'Gujarat Technological University'), ('HNGU', 'Hemchandracharya North Gujarat University'), ('other', 'Other')], max_length=100),
        ),
    ]
