# Generated by Django 4.2 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_image_project_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='AcademicHub', max_length=100)),
                ('contact_email', models.EmailField(default='admin@academichub.com', max_length=254)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='oldpaper',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('M.Tech', 'Master of Technology'), ('Diploma', 'Diploma in Engineering'), ('B.E', 'Bachelor of Engineering'), ('M.E', 'Master of Engineering'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('B.Com', 'Bachelor of Commerce'), ('M.Com', 'Master of Commerce'), ('B.Sc', 'Bachelor of Science'), ('M.Sc', 'Master of Science'), ('B.A', 'Bachelor of Arts'), ('M.A', 'Master of Arts'), ('B.Ed', 'Bachelor of Education'), ('M.Ed', 'Master of Education'), ('LLB', 'Bachelor of Law'), ('LLM', 'Master of Law'), ('B.Pharm', 'Bachelor of Pharmacy'), ('M.Pharm', 'Master of Pharmacy'), ('B.Arch', 'Bachelor of Architecture'), ('BFA', 'Bachelor of Fine Arts'), ('BJMC', 'Bachelor of Journalism and Mass Communication'), ('B.P.Ed', 'Bachelor of Physical Education'), ('M.P.Ed', 'Master of Physical Education'), ('BDS', 'Bachelor of Dental Surgery'), ('BHMS', 'Bachelor of Homeopathic Medicine and Surgery'), ('B.Voc', 'Bachelor of Vocation'), ('B.Lib.I.Sc', 'Bachelor of Library and Information Science'), ('M.Lib', 'Master of Library Science'), ('M.Phil', 'Master of Philosophy'), ('Ph.D', 'Doctor of Philosophy'), ('PGD', 'Post Graduate Diploma'), ('Diploma (Other)', 'Diploma (Others)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='oldpaper',
            name='university',
            field=models.CharField(choices=[('GTU', 'Gujarat Technological University'), ('HNGU', 'Hemchandracharya North Gujarat University'), ('SPU', 'Sardar Patel University'), ('MSU', 'The Maharaja Sayajirao University of Baroda'), ('GU', 'Gujarat University'), ('PU', 'Parul University'), ('NFSU', 'National Forensic Sciences University'), ('KSU', 'Krantiguru Shyamji Krishna Verma Kachchh University'), ('PDPU', 'Pandit Deendayal Energy University (formerly PDPU)'), ('DGU', 'Dharmsinh Desai University'), ('SU', 'Sumandeep Vidyapeeth'), ('RKDU', 'Raksha Shakti University'), ('UKU', 'Uka Tarsadia University'), ('CU', 'Charotar University of Science and Technology (CHARUSAT)'), ('INDU', 'Indian Institute of Teacher Education (IITE)'), ('DAIICT', 'Dhirubhai Ambani Institute of Information and Communication Technology'), ('NID', 'National Institute of Design'), ('IITGN', 'Indian Institute of Technology Gandhinagar'), ('IIM', 'Indian Institute of Management Ahmedabad'), ('AIIMS', 'All India Institute of Medical Sciences Rajkot'), ('GNLU', 'Gujarat National Law University'), ('SVNIT', 'Sardar Vallabhbhai National Institute of Technology, Surat'), ('VU', 'Vidyapith Universities (Gujarat Vidyapith, Saurashtra University, etc.)'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('R', 'R'), ('Dart', 'Dart'), ('Rust', 'Rust'), ('SQL', 'SQL'), ('Shell', 'Shell'), ('Perl', 'Perl'), ('MATLAB', 'MATLAB'), ('Scala', 'Scala'), ('Haskell', 'Haskell'), ('Objective-C', 'Objective-C'), ('Visual Basic', 'Visual Basic'), ('Assembly', 'Assembly'), ('Other', 'Other')], default='other', max_length=50),
        ),
    ]
