# Generated by Django 4.2 on 2025-07-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blog_view_count_oldpaper_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='oldpaper',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='download_count',
        ),
        migrations.DeleteModel(
            name='DownloadLog',
        ),
    ]
