# Generated by Django 4.2 on 2025-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_blog_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpaper',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_zip_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldpaper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
