# Generated by Django 4.2 on 2025-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_oldpaper_github_link_project_github_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldpaper',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_zip_url',
        ),
        migrations.AlterField(
            model_name='oldpaper',
            name='file',
            field=models.FileField(default='no-paper.pdf', upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FileField(default='no-project.zip', upload_to='projects/'),
        ),
    ]
