# Generated by Django 4.2 on 2025-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_oldpaper_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpaper',
            name='file',
            field=models.FileField(upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
