# Generated by Django 4.2 on 2025-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_oldpaper_file_alter_project_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpaper',
            name='file',
            field=models.FileField(default='no-paper.pdf', upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_file',
            field=models.FileField(default='no-project.zip', upload_to='projects/'),
        ),
    ]
