# Generated by Django 4.2 on 2025-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_oldpaper_file_alter_project_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
