# Generated by Django 4.2 on 2025-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_telegram_file_id_project_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloudinary_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
