# Generated by Django 4.2 on 2025-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_cloudinary_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldpaper',
            name='file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cloudinary_file_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='telegram_file_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='telegram_link',
        ),
        migrations.AddField(
            model_name='oldpaper',
            name='drive_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
