# Generated by Django 4.2 on 2025-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_oldpaper_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
